---
areaConfigurations:
- areaCode: "ad"
  csvConfiguration:
    electoralListIds:
    - "AD001"
    - "AD002"
    - "AD002+AD003"
    - "AD005"
    - "AD004"
    - "AD007"
    - "AD007+AD008"
    - "AD003"
    - "AD009"
    - "AD010"
    - "AD011"
    - "AD012"
    - "AD006"
    - "AD001+AD010+AD011+AD015"
    - "AD002+AD004"
    - "AD013"
    - "AD014"
  elections:
    national:
      dates:
        3: "2001-03-04"
        4: "2005-04-24"
        5: "2009-04-26"
        6: "2011-04-03"
        7: "2015-03-01"
        8: "2019-04-07"
        9: "2023-04-02"
  translations:
    de: "Andorra"
    en: "Andorra"
    eo: "Andoro"
    fr: "Andorre"
    nl: "Andorra"
    no: "Andorra"
- areaCode: "al"
  elections:
    national:
      dates:
        26: "2001-06-24+2001-07-08"
        27: "2005-07-03"
        28: "2009-06-28"
        29: "2013-06-23"
        30: "2017-06-25"
        31: "2021-04-25"
        32: "≤2025-04"
  translations:
    de: "Albanien"
    en: "Albania"
    eo: "Albanio"
    fr: "Albanie"
    nl: "Albanië"
    no: "Albania"
- areaCode: "am"
  elections:
    national:
      dates:
        3: "2003-05-25"
        4: "2007-05-12"
        5: "2012-05-06"
        6: "2017-04-02"
        7: "2018-12-09"
        8: "2021-06-20"
        9: "≤2026-06"
  translations:
    de: "Armenien"
    en: "Armenia"
    eo: "Armenio"
    fr: "Arménie"
    nl: "Armenië"
    no: "Armenia"
- areaCode: "at"
  elections:
    european:
      dates:
        3: "2004-06-13"
        4: "2009-06-04"
        5: "2014-05-25"
        6: "2019-05-26"
        7: "≈2024-06-09"
    national:
      dates:
        22: "2002-11-24"
        23: "2006-10-01"
        24: "2008-09-28"
        25: "2013-09-29"
        26: "2017-10-15"
        27: "2019-09-29"
        28: "≤2024-10-27"
      gitHubWebsiteUrl: "https://filipvanlaenen.github.io/austrian_polls"
    presidential:
      dates:
        11: "2004-04-25"
        12: "2010-04-25"
        13: "2016-04-24+(2016-05-22)+2016-12-04"
        14: "2022-10-09"
        15: "≈2028-10"
  translations:
    de: "Österreich"
    en: "Austria"
    eo: "Aŭstrio"
    fr: "Autriche"
    nl: "Oostenrijk"
    no: "Østerrike"
- areaCode: "ax"
  elections:
    national:
      dates:
        0: "≤2023-10"
  translations:
    de: "Åland"
    en: "Åland"
    eo: "Alando"
    fr: "Åland"
    nl: "Åland"
    no: "Åland"
- areaCode: "az"
  elections:
    national:
      dates:
        0: "≤2025-02"
    presidential:
      dates:
        0: "≈2025"
  translations:
    de: "Aserbaidschan"
    en: "Azerbaijan"
    eo: "Azerbajĝano"
    fr: "Azerbaïdjan"
    nl: "Azerbeidzjan"
    no: "Aserbajdsjan"
- areaCode: "ba"
  elections:
    national:
      dates:
        0: "≤2026-10"
    presidential:
      dates:
        0: "≤2026-10"
  translations:
    de: "Bosnien und Herzegowina"
    en: "Bosnia and Herzegovina"
    eo: "Bosnio kaj Hercegovino"
    fr: "Bosnie-Herzégovine"
    nl: "Bosnië en Herzegovina"
    no: "Bosnia-Hercegovina"
- areaCode: "be"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "⪅2024-06-09"
      gitHubWebsiteUrl: "https://filipvanlaenen.github.io/belgian_polls"
  translations:
    de: "Belgien"
    en: "Belgium"
    eo: "Belgio"
    fr: "Belgique"
    nl: "België"
    no: "Belgia"
- areaCode: "bg"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "2023-04-02"
    presidential:
      dates:
        0: "≈2026-11"
  translations:
    de: "Bulgarien"
    en: "Bulgaria"
    eo: "Bulgario"
    fr: "Bulgarie"
    nl: "Bulgarije"
    no: "Bulgaria"
- areaCode: "by"
  elections:
    national:
      dates:
        0: "≤2023-11"
    presidential:
      dates:
        0: "≤2025-08"
  translations:
    de: "Belarus"
    en: "Belarus"
    eo: "Belorusio"
    fr: "Biélorussie"
    nl: "Wit-Rusland"
    no: "Belarus"
- areaCode: "ch"
  csvConfiguration:
    electoralListIds:
    - "CH003"
    - "CH001"
    - "CH002"
    - "CH017"
    - "CH005"
    - "CH012"
    - "CH007"
    - "CH010"
    - "CH009"
    - "CH013"
    - "CH008"
    - "CH016"
    - "CH004"
    - "CH015"
    - "CH014"
    - "CH011"
    - "CH006"
  elections:
    national:
      dates:
        0: "2023-10-22"
  translations:
    de: "Schweiz"
    en: "Switzerland"
    eo: "Svislando"
    fr: "Suisse"
    nl: "Zwitserland"
    no: "Sveits"
- areaCode: "cy"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2026-06"
    presidential:
      dates:
        0: "≈2028-02"
  translations:
    de: "Zypern"
    en: "Cyprus"
    eo: "Kipro"
    fr: "Chypre"
    nl: "Cyprus"
    no: "Kypros"
- areaCode: "cz"
  elections:
    european:
      dates:
        0: "≈2024-06-08"
    national:
      dates:
        0: "≤2025-10"
    presidential:
      dates:
        0: "≤2028-01"
  translations:
    de: "Tschechien"
    en: "Czechia"
    eo: "Ĉeĥio"
    fr: "Tchéquie"
    nl: "Tsjechië"
    no: "Tsjekkia"
- areaCode: "de"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2025-10-26"
  translations:
    de: "Deutschland"
    en: "Germany"
    eo: "Germanio"
    fr: "Allemagne"
    nl: "Duitsland"
    no: "Tyskland"
- areaCode: "dk"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2026-11-01"
  translations:
    de: "Dänemark"
    en: "Denmark"
    eo: "Danio"
    fr: "Danemark"
    nl: "Denemarken"
    no: "Danmark"
- areaCode: "ee"
  csvConfiguration:
    electoralListIds:
    - "EE001"
    - "EE002"
    - "EE004"
    - "EE006"
    - "EE005"
    - "EE003"
    - "EE007"
    - "EE008"
    - "EE009"
    - "EE011"
    - "EE010"
    - "EE012"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2027-03-07"
      gitHubWebsiteUrl: "https://filipvanlaenen.github.io/estonian_polls"
  translations:
    de: "Estland"
    en: "Estonia"
    eo: "Estonio"
    fr: "Estonie"
    nl: "Estland"
    no: "Estland"
- areaCode: "es"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2023-12-10"
  translations:
    de: "Spanien"
    en: "Spain"
    eo: "Hispanio"
    fr: "Espagne"
    nl: "Spanje"
    no: "Spania"
- areaCode: "fi"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "2023-04-02"
    presidential:
      dates:
        0: "≈2024-01"
  translations:
    de: "Finnland"
    en: "Finland"
    eo: "Finnlando"
    fr: "Finlande"
    nl: "Finland"
    no: "Finland"
- areaCode: "fo"
  csvConfiguration:
    electoralListIds:
    - "FO001"
    - "FO002"
    - "FO003"
    - "FO004"
    - "FO005"
    - "FO006"
    - "FO007"
  elections:
    national:
      dates:
        0: "≤2026-12"
  translations:
    de: "Färöer"
    en: "Faroe Islands"
    eo: "Ferooj"
    fr: "Îles Féroé"
    nl: "Faeröer"
    no: "Færøyene"
- areaCode: "fr"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2027-06"
    presidential:
      dates:
        0: "≈2027-04"
  translations:
    de: "Frankreich"
    en: "France"
    eo: "Francio"
    fr: "France"
    nl: "Frankrijk"
    no: "Frankrike"
- areaCode: "gb"
  elections:
    national:
      dates:
        0: "≤2025-01"
      gitHubWebsiteUrl: "https://filipvanlaenen.github.io/british_polls"
  translations:
    de: "Vereinigtes Königreich"
    en: "United Kingdom"
    eo: "Unuiĝinta Reĝlando"
    fr: "Royaume-Uni"
    nl: "Verenigd Koninkrijk"
    no: "Det forente kongerike"
- areaCode: "ge"
  elections:
    national:
      dates:
        0: "≤2024-10"
  translations:
    de: "Georgien"
    en: "Georgia"
    eo: "Kartvelio"
    fr: "Géorgie"
    nl: "Georgië"
    no: "Georgia"
- areaCode: "gi"
  elections:
    national:
      dates:
        0: "≤2023-10"
  translations:
    de: "Gibraltar"
    en: "Gibraltar"
    eo: "Ĝibraltaro"
    fr: "Gibraltar"
    nl: "Gibraltar"
    no: "Gibraltar"
- areaCode: "gl"
  csvConfiguration:
    electoralListIds:
    - "GL002"
    - "GL001"
    - "GL003"
    - "GL004"
    - "GL006"
    - "GL005"
    - "GL007"
  elections:
    national:
      dates:
        0: "≤2025-04-06"
  translations:
    de: "Grönland"
    en: "Greenland"
    eo: "Gronlando"
    fr: "Groenland"
    nl: "Groenland"
    no: "Grønland"
- areaCode: "gr"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2023-07"
      gitHubWebsiteUrl: "https://filipvanlaenen.github.io/greek_polls"
  translations:
    de: "Griechenland"
    en: "Greece"
    eo: "Grekio"
    fr: "Grèce"
    nl: "Griekenland"
    no: "Hellas"
- areaCode: "hr"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2024-07-22"
    presidential:
      dates:
        0: "≈2024-12"
  translations:
    de: "Kroatien"
    en: "Croatia"
    eo: "Kroatio"
    fr: "Croatie"
    nl: "Kroatië"
    no: "Kroatia"
- areaCode: "hu"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2026-04"
  translations:
    de: "Ungarn"
    en: "Hungary"
    eo: "Hungario"
    fr: "Hongrie"
    nl: "Hongarije"
    no: "Ungarn"
- areaCode: "ie"
  elections:
    european:
      dates:
        0: "≈2024-06-07"
    national:
      dates:
        0: "≤2025-03"
    presidential:
      dates:
        0: "≈2025-10"
  translations:
    de: "Irland"
    en: "Ireland"
    eo: "Irlando"
    fr: "Irlande"
    nl: "Ierland"
    no: "Irland"
- areaCode: "is"
  elections:
    national:
      dates:
        0: "≤2025-09-27"
    presidential:
      dates:
        0: "≈2024-06"
  translations:
    de: "Island"
    en: "Iceland"
    eo: "Islando"
    fr: "Islande"
    nl: "IJsland"
    no: "Island"
- areaCode: "it"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2027-12-22"
  translations:
    de: "Italien"
    en: "Italy"
    eo: "Italio"
    fr: "Italie"
    nl: "Italië"
    no: "Italia"
- areaCode: "kz"
  elections:
    national:
      dates:
        0: "2023-03-19"
    presidential:
      dates:
        0: "≈2029-11"
  translations:
    de: "Kasachstan"
    en: "Kazakhstan"
    eo: "Kazaĥio"
    fr: "Kazakhstan"
    nl: "Kazachstan"
    no: "Kasakhstan"
- areaCode: "li"
  elections:
    national:
      dates:
        0: "≤2025-02"
  translations:
    de: "Liechtenstein"
    en: "Liechtenstein"
    eo: "Liĥtenŝtejno"
    fr: "Liechtenstein"
    nl: "Liechtenstein"
    no: "Liechtenstein"
- areaCode: "lt"
  csvConfiguration:
    electoralListIds:
    - "LT002"
    - "LT001"
    - "LT005"
    - "LT003"
    - "LT004"
    - "LT006"
    - "LT008"
    - "LT007"
    - "LT009"
    - "LT010"
    - "LT011"
    - "LT012"
    - "LT013"
    - "LT014"
    - "LT015"
    - "LT016"
    - "LT017"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2024-10-06"
    presidential:
      dates:
        0: "≈2024-05"
  translations:
    de: "Litauen"
    en: "Lithuania"
    eo: "Litovio"
    fr: "Lituanie"
    nl: "Litouwen"
    no: "Litauen"
- areaCode: "lu"
  csvConfiguration:
    electoralListIds:
    - "LU001"
    - "LU002"
    - "LU004"
    - "LU003"
    - "LU005"
    - "LU006"
    - "LU007"
    - "LU009"
    - "LU008"
    - "LU011"
    - "LU010"
    - "LU012"
    - "LU013"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2023-10"
      gitHubWebsiteUrl: "https://filipvanlaenen.github.io/luxembourg_polls/"
  translations:
    de: "Luxemburg"
    en: "Luxembourg"
    eo: "Luksemburgo"
    fr: "Luxembourg"
    nl: "Luxemburg"
    no: "Luxembourg"
- areaCode: "lv"
  csvConfiguration:
    electoralListIds:
    - "LV001"
    - "LV002"
    - "LV003"
    - "LV004"
    - "LV005"
    - "LV006"
    - "LV007"
    - "LV008"
    - "LV009"
    - "LV010"
    - "LV011"
    - "LV012"
    - "LV013"
    - "LV014"
    - "LV015"
    - "LV016"
    - "LV017"
    - "LV018"
    - "LV019"
  elections:
    european:
      dates:
        0: "≈2024-06-08"
    national:
      dates:
        0: "≤2026-10"
  translations:
    de: "Lettland"
    en: "Latvia"
    eo: "Latvio"
    fr: "Lettonie"
    nl: "Letland"
    no: "Latvia"
- areaCode: "mc"
  elections:
    national:
      dates:
        0: "≤2028-02"
  translations:
    de: "Monaco"
    en: "Monaco"
    eo: "Monako"
    fr: "Monaco"
    nl: "Monaco"
    no: "Monaco"
- areaCode: "md"
  csvConfiguration:
    electoralListIds:
    - "MD001"
    - "MD002"
    - "MD003"
    - "MD004"
    - "MD005"
    - "MD007"
    - "MD008"
    - "MD006"
    - "MD010"
    - "MD009"
    - "MD011"
  elections:
    national:
      dates:
        0: "≤2025-07"
    presidential:
      dates:
        0: "≈2024-11"
  translations:
    de: "Moldau"
    en: "Moldavio"
    eo: "Moldavia"
    fr: "Moldavie"
    nl: "Moldavië"
    no: "Moldova"
- areaCode: "me"
  elections:
    national:
      dates:
        0: "≤2024-08"
    presidential:
      dates:
        0: "2023-03-19"
  translations:
    de: "Montenegro"
    en: "Montenegro"
    eo: "Montenegro"
    fr: "Monténégro"
    nl: "Montenegro"
    no: "Montenegro"
- areaCode: "mk"
  csvConfiguration:
    electoralListIds:
    - "MK002"
    - "MK001"
    - "MK003"
    - "MK004"
    - "MK005"
    - "MK008"
    - "MK006"
    - "MK007"
    - "MK007+MK004"
    - "MK009+MK010"
  elections:
    national:
      dates:
        0: "≤2024-07-15"
    presidential:
      dates:
        0: "≤2024-04-21"
  translations:
    de: "Nordmazedonien"
    en: "North Macedonia"
    eo: "Nord-Makedonio"
    fr: "Macédoine du Nord"
    nl: "Noord-Macedonië"
    no: "Nord-Makedonia"
- areaCode: "mt"
  elections:
    european:
      dates:
        0: "≈2024-06-08"
    national:
      dates:
        0: "≤2027-03"
  translations:
    de: "Malta"
    en: "Malta"
    eo: "Malto"
    fr: "Malte"
    nl: "Malta"
    no: "Malta"
- areaCode: "nl"
  elections:
    european:
      dates:
        0: "≈2024-06-06"
    national:
      dates:
        0: "≤2025-03"
      gitHubWebsiteUrl: "https://filipvanlaenen.github.io/dutch_polls"
  translations:
    de: "Niederlande"
    en: "Netherlands"
    eo: "Nederlando"
    fr: "Pays-Bas"
    nl: "Nederland"
    no: "Nederland"
- areaCode: "no"
  elections:
    national:
      dates:
        0: "2025-09"
  translations:
    de: "Norwegen"
    en: "Norway"
    eo: "Norvegio"
    fr: "Norvège"
    nl: "Noorwegen"
    no: "Norge"
- areaCode: "pl"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2023-10"
    presidential:
      dates:
        0: "≤2025-07"
  translations:
    de: "Polen"
    en: "Poland"
    eo: "Pollando"
    fr: "Pologne"
    nl: "Polen"
    no: "Polen"
- areaCode: "pt"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2026-10-11"
    presidential:
      dates:
        0: "≈2026-01"
  translations:
    de: "Portugal"
    en: "Portugal"
    eo: "Portugalio"
    fr: "Portugal"
    nl: "Portugal"
    no: "Portugal"
- areaCode: "ro"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2025-03-21"
      gitHubWebsiteUrl: "https://filipvanlaenen.github.io/romanian_polls"
    presidential:
      dates:
        0: "≈2024-11"
  translations:
    de: "Rumänien"
    en: "Romania"
    eo: "Rumanio"
    fr: "Roumanie"
    nl: "Roemenië"
    no: "Romania"
- areaCode: "rs"
  csvConfiguration:
    electoralListIds:
    - "RS001"
    - "RS003"
    - "RS003+RS014"
    - "RS004"
    - "RS010"
    - "RS002"
    - "RS006"
    - "RS006+RS007"
    - "RS005"
    - "RS008"
    - "RS011"
    - "RS009"
    - "RS012"
    - "RS013"
  elections:
    national:
      dates:
        0: "≤2026-04-03"
    presidential:
      dates:
        0: "≤2027-04-03"
  translations:
    de: "Serbien"
    en: "Serbia"
    eo: "Serbio"
    fr: "Serbie"
    nl: "Servië"
    no: "Serbia"
- areaCode: "ru"
  elections:
    national:
      dates:
        0: "≤2026-09-20"
    presidential:
      dates:
        0: "2024-03-17"
  translations:
    de: "Russland"
    en: "Russia"
    eo: "Rusio"
    fr: "Russie"
    nl: "Rusland"
    no: "Russland"
- areaCode: "se"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "2026-09-13"
  translations:
    de: "Schweden"
    en: "Sweden"
    eo: "Svedio"
    fr: "Suède"
    nl: "Zweden"
    no: "Sverige"
- areaCode: "si"
  elections:
    european:
      dates:
        0: "≈2024-06-09"
    national:
      dates:
        0: "≤2026-04-24"
      gitHubWebsiteUrl: "https://filipvanlaenen.github.io/slovenian_polls"
    presidential:
      dates:
        0: "≈2027-11"
  translations:
    de: "Slowenien"
    en: "Slovenia"
    eo: "Slovenio"
    fr: "Slovénie"
    nl: "Slovenië"
    no: "Slovenia"
- areaCode: "sk"
  elections:
    european:
      dates:
        0: "≈2024-06-08"
    national:
      dates:
        0: "2023-09-30"
      gitHubWebsiteUrl: "https://filipvanlaenen.github.io/slovakian_polls"
    presidential:
      dates:
        0: "≈2024-03"
  translations:
    de: "Slowakei"
    en: "Slovakia"
    eo: "Slovakio"
    fr: "Slovaquie"
    nl: "Slovakije"
    no: "Slovakia"
- areaCode: "sm"
  elections:
    national:
      dates:
        0: "≤2024-12"
  translations:
    de: "San Marino"
    en: "San Marino"
    eo: "San-Marino"
    fr: "Saint Marin"
    nl: "San Marino"
    no: "San Marino"
- areaCode: "tr"
  elections:
    national:
      dates:
        0: "2023-05-14"
    presidential:
      dates:
        0: "2023-05-14"
  translations:
    de: "Türkei"
    en: "Turkey"
    eo: "Turkio"
    fr: "Turquie"
    nl: "Turkije"
    no: "Tyrkia"
- areaCode: "ua"
  elections:
    national:
      dates:
        0: "≤2023-10-29"
    presidential:
      dates:
        0: "2024-03-31"
  translations:
    de: "Ukraine"
    en: "Ukraine"
    eo: "Ukrainio"
    fr: "Ukraine"
    nl: "Oekraïne"
    no: "Ukraina"
- areaCode: "xk"
  csvConfiguration:
    electoralListIds:
    - "XK002"
    - "XK001"
    - "XK003"
    - "XK004"
    - "XK009"
    - "XK006"
    - "XK011"
    - "XK010"
    - "XK007"
    - "XK005"
    - "XK004+XK005"
    - "XK006+XK007+XK008"
  elections:
    national:
      dates:
        0: "≤2025-02"
  translations:
    de: "Kosovo"
    en: "Kosovo"
    eo: "Kosovo"
    fr: "Kosovo"
    nl: "Kosovo"
    no: "Kosovo"
