---
areaConfigurations:
- areaCode: "ad"
  electionConfigurations:
  - nextElectionDate: "≤2023-04"
    type: Parliament
  translations:
    de: "Andorra"
    en: "Andorra"
    eo: "Andoro"
    fr: "Andorre"
    nl: "Andorra"
    no: "Andorra"
- areaCode: "al"
  electionConfigurations:
  - nextElectionDate: "≤2025-04"
    type: Parliament
  translations:
    de: "Albanien"
    en: "Albania"
    eo: "Albanio"
    fr: "Albanie"
    nl: "Albanië"
    no: "Albania"
- areaCode: "am"
  electionConfigurations:
  - nextElectionDate: "≤2026-06"
    type: Parliament
  translations:
    de: "Armenien"
    en: "Armenia"
    eo: "Armenio"
    fr: "Arménie"
    nl: "Armenië"
    no: "Armenia"
- areaCode: "at"
  electionConfigurations:
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  - gitHubWebsiteUrl: "https://filipvanlaenen.github.io/austrian_polls"
    nextElectionDate: "≤2024-10-27"
    type: Parliament
  - nextElectionDate: "≈2028-10"
    type: President
  translations:
    de: "Österreich"
    en: "Austria"
    eo: "Aŭstrio"
    fr: "Autriche"
    nl: "Oostenrijk"
    no: "Østerrike"
- areaCode: "az"
  electionConfigurations:
  - nextElectionDate: "≤2025-02"
    type: Parliament
  - nextElectionDate: "≈2025"
    type: President
  translations:
    de: "Aserbaidschan"
    en: "Azerbaijan"
    eo: "Azerbajĝano"
    fr: "Azerbaïdjan"
    nl: "Azerbeidzjan"
    no: "Aserbajdsjan"
- areaCode: "ba"
  electionConfigurations:
  - nextElectionDate: "≤2026-10"
    type: Parliament
  - nextElectionDate: "≤2026-10"
    type: President
  translations:
    de: "Bosnien und Herzegowina"
    en: "Bosnia and Herzegovina"
    eo: "Bosnio kaj Hercegovino"
    fr: "Bosnie-Herzégovine"
    nl: "Bosnië en Herzegovina"
    no: "Bosnia-Hercegovina"
- areaCode: "be"
  electionConfigurations:
  - gitHubWebsiteUrl: "https://filipvanlaenen.github.io/belgian_polls"
    nextElectionDate: "≈2024-05"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Belgien"
    en: "Belgium"
    eo: "Belgio"
    fr: "Belgique"
    nl: "België"
    no: "Belgia"
- areaCode: "bg"
  electionConfigurations:
  - nextElectionDate: "≤2026-10"
    type: Parliament
  - nextElectionDate: "≈2026-11"
    type: President
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Bulgarien"
    en: "Bulgaria"
    eo: "Bulgario"
    fr: "Bulgarie"
    nl: "Bulgarije"
    no: "Bulgaria"
- areaCode: "by"
- areaCode: "ch"
  electionConfigurations:
  - nextElectionDate: "2023-02-05"
    type: President
  - nextElectionDate: "2023-10-22"
    type: Parliament
  translations:
    de: "Schweiz"
    en: "Switzerland"
    eo: "Svislando"
    fr: "Suisse"
    nl: "Zwitserland"
    no: "Sveits"
- areaCode: "cy"
  electionConfigurations:
  - nextElectionDate: "2023-02-05"
    type: President
  - nextElectionDate: "≤2026-06"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Zypern"
    en: "Cyprus"
    eo: "Kipro"
    fr: "Chypre"
    nl: "Cyprus"
    no: "Kypros"
- areaCode: "cz"
  electionConfigurations:
  - nextElectionDate: "2023-01-14"
    type: President
  - nextElectionDate: "≤2025-10"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Tschechien"
    en: "Czechia"
    eo: "Ĉeĥio"
    fr: "Tchéquie"
    nl: "Tsjechië"
    no: "Tsjekkia"
- areaCode: "de"
  electionConfigurations:
  - nextElectionDate: "≤2025-10-26"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Deutschland"
    en: "Germany"
    eo: "Germanio"
    fr: "Allemagne"
    nl: "Duitsland"
    no: "Tyskland"
- areaCode: "dk"
  electionConfigurations:
  - gitHubWebsiteUrl: "https://filipvanlaenen.github.io/danish_polls"
    nextElectionDate: "2022-11-01"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Dänemark"
    en: "Denmark"
    eo: "Danio"
    fr: "Danemark"
    nl: "Denemarken"
    no: "Danmark"
- areaCode: "ee"
  electionConfigurations:
  - gitHubWebsiteUrl: "https://filipvanlaenen.github.io/estonian_polls"
    nextElectionDate: "2023-03-05"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Estland"
    en: "Estonia"
    eo: "Estonio"
    fr: "Estonie"
    nl: "Estland"
    no: "Estland"
- areaCode: "es"
  electionConfigurations:
  - nextElectionDate: "≤2023-12-10"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Spanien"
    en: "Spain"
    eo: "Hispanio"
    fr: "Espagne"
    nl: "Spanje"
    no: "Spania"
- areaCode: "fi"
  electionConfigurations:
  - nextElectionDate: "≈2024-01"
    type: President
  - nextElectionDate: "≤2023-04-02"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Finnland"
    en: "Finland"
    eo: "Finnlando"
    fr: "Finlande"
    nl: "Finland"
    no: "Finland"
- areaCode: "fo"
- areaCode: "fr"
  electionConfigurations:
  - nextElectionDate: "≈2027-04"
    type: President
  - nextElectionDate: "≤2027-06"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Frankreich"
    en: "France"
    eo: "Francio"
    fr: "France"
    nl: "Frankrijk"
    no: "Frankrike"
- areaCode: "gb"
  electionConfigurations:
  - gitHubWebsiteUrl: "https://filipvanlaenen.github.io/british_polls"
    nextElectionDate: "≤2025-01"
    type: Parliament
  translations:
    de: "Vereinigtes Königreich"
    en: "United Kingdom"
    eo: "Unuiĝinta Reĝlando"
    fr: "Royaume-Uni"
    nl: "Verenigd Koninkrijk"
    no: "Det forente kongerike"
- areaCode: "ge"
- areaCode: "gl"
  csvConfiguration:
    electoralListKeys:
    - "S"
    - "IA"
    - "D"
    - "N"
    - "A"
    - "NQ"
    - "SA"
  electionConfigurations:
  - nextElectionDate: "≤2025-04-06"
    type: Parliament
  translations:
    de: "Grönland"
    en: "Greenland"
    eo: "Gronlando"
    fr: "Groenland"
    nl: "Groenland"
    no: "Grønland"
- areaCode: "gr"
  electionConfigurations:
  - gitHubWebsiteUrl: "https://filipvanlaenen.github.io/greek_polls"
    nextElectionDate: "≤2023-07"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Griechenland"
    en: "Greece"
    eo: "Grekio"
    fr: "Grèce"
    nl: "Griekenland"
    no: "Hellas"
- areaCode: "hr"
- areaCode: "hu"
- areaCode: "ie"
- areaCode: "is"
- areaCode: "it"
- areaCode: "kz"
- areaCode: "li"
- areaCode: "lt"
- areaCode: "lu"
  electionConfigurations:
  - gitHubWebsiteUrl: "https://filipvanlaenen.github.io/luxembourg_polls/"
    nextElectionDate: "≤2023-10"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Luxemburg"
    en: "Luxembourg"
    eo: "Luksemburgo"
    fr: "Luxembourg"
    nl: "Luxemburg"
    no: "Luxembourg"
- areaCode: "lv"
  electionConfigurations:
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  - nextElectionDate: "≤2026-10"
    type: Parliament
  translations:
    de: "Lettland"
    en: "Latvia"
    eo: "Latvio"
    fr: "Lettonie"
    nl: "Letland"
    no: "Latvia"
- areaCode: "mc"
  electionConfigurations:
  - nextElectionDate: "2023-02-05"
    type: Parliament
  translations:
    de: "Monaco"
    en: "Monaco"
    eo: "Monako"
    fr: "Monaco"
    nl: "Monaco"
    no: "Monaco"
- areaCode: "md"
- areaCode: "me"
  electionConfigurations:
  - nextElectionDate: "≈2023-04"
    type: President
  - nextElectionDate: "≤2024-08"
    type: Parliament
  translations:
    de: "Montenegro"
    en: "Montenegro"
    eo: "Montenegro"
    fr: "Monténégro"
    nl: "Montenegro"
    no: "Montenegro"
- areaCode: "mk"
  csvConfiguration:
    electoralListKeys:
    - "СДСМ"
    - "ВМРО"
    - "ДУИ"
    - "ASH"
    - "ЛЕВ"
    - "PDSH"
    - "BESA"
    - "A"
    - "A+ASH"
    - "ДОМ+ЛДП"
  electionConfigurations:
  - nextElectionDate: "≤2024-07-15"
    type: Parliament
  - nextElectionDate: "≤2024-04-21"
    type: President
  translations:
    de: "Nordmazedonien"
    en: "North Macedonia"
    eo: "Nord-Makedonio"
    fr: "Macédoine du Nord"
    nl: "Noord-Macedonië"
    no: "Nord-Makedonia"
- areaCode: "mt"
- areaCode: "nl"
  electionConfigurations:
  - gitHubWebsiteUrl: "https://filipvanlaenen.github.io/dutch_polls"
    nextElectionDate: "≤2025-03"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Niederlande"
    en: "Netherlands"
    eo: "Nederlando"
    fr: "Pays-Bas"
    nl: "Nederland"
    no: "Nederland"
- areaCode: "no"
- areaCode: "pl"
- areaCode: "pt"
- areaCode: "ro"
  electionConfigurations:
  - gitHubWebsiteUrl: "https://filipvanlaenen.github.io/romanian_polls"
    nextElectionDate: "≤2025-03-21"
    type: Parliament
  - nextElectionDate: "≈2024-11"
    type: President
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Rumänien"
    en: "Romania"
    eo: "Rumanio"
    fr: "Roumanie"
    nl: "Roemenië"
    no: "Romania"
- areaCode: "rs"
  csvConfiguration:
    electoralListKeys:
    - "СНС"
    - "СПС"
    - "СПС+ЈС"
    - "НДСС"
    - "СРЦЕ"
    - "ССП"
    - "ЗЗС"
    - "ЗЗС+НДБГД"
    - "ДВЕРИ"
    - "ССЗ"
    - "СДС"
    - "ДС"
    - "НС"
    - "ПСГ"
  electionConfigurations:
  - nextElectionDate: "≤2026-04-03"
    type: Parliament
  - nextElectionDate: "≤2027-04-03"
    type: President
  translations:
    de: "Serbien"
    en: "Serbia"
    eo: "Serbio"
    fr: "Serbie"
    nl: "Servië"
    no: "Serbia"
- areaCode: "ru"
- areaCode: "se"
- areaCode: "si"
  electionConfigurations:
  - gitHubWebsiteUrl: "https://filipvanlaenen.github.io/slovenian_polls"
    nextElectionDate: "≤2026-04-24"
    type: Parliament
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  - nextElectionDate: "2022-11-13"
    type: President
  translations:
    de: "Slowenien"
    en: "Slovenia"
    eo: "Slovenio"
    fr: "Slovénie"
    nl: "Slovenië"
    no: "Slovenia"
- areaCode: "sk"
  electionConfigurations:
  -  gitHubWebsiteUrl: "https://filipvanlaenen.github.io/slovakian_polls"
     nextElectionDate: "≤2024-02-24"
     type: Parliament
  -  nextElectionDate: "≈2024-03"
     type: President
  - nextElectionDate: "≈2024-05"
    type: European Parliament
  translations:
    de: "Slowakei"
    en: "Slovakia"
    eo: "Slovakio"
    fr: "Slovaquie"
    nl: "Slovakije"
    no: "Slovakia"
- areaCode: "sm"
- areaCode: "tr"
  electionConfigurations:
  - nextElectionDate: "2023-06-18"
    type: Parliament
  - nextElectionDate: "2023-06-18"
    type: President
  translations:
    de: "Türkei"
    en: "Turkey"
    eo: "Turkio"
    fr: "Turquie"
    nl: "Turkije"
    no: "Tyrkia"
- areaCode: "ua"
- areaCode: "xk"
